name: CI

on: push

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bun-version: [latest, '1.1.3']
    name: Test Builds
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Codebase
        uses: ./ #hudsonm62/prettier@v1
        with:
          args: --check .

      - name: Setup Bun (Node)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install Deps
        run: bun install --frozen-lockfile --production

      - name: Bundle Node Build
        run: bun run build

      - name: Compile Binary Build
        run: bun run package

  verify-output:
    strategy:
      matrix:
        os: [ubuntu-latest]
        bun-version: [latest, '1.1.3']
    name: Verify Output
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun (Node)
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Install Deps
        run: bun install --frozen-lockfile --production
      - name: Build Node Comparison
        run: |
          bun build ./index.js --target node --minify --outfile ./dist-ci/node-prettier.mjs

      - name: Verify output
        run: diff -qr dist dist-ci

  test-action:
    needs: verify-output
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Test Action
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun (Node)
        uses: oven-sh/setup-bun@v1

      - name: Fresh Rebuild
        run: |
          bun install --frozen-lockfile --production
          bun run build

      - name: prettier --version
        uses: ./
        with:
          args: --version
      - name: prettier --help
        uses: ./
        with:
          args: --help
      - name: prettier --check .
        uses: ./
        with:
          args: --check .
      - name: prettier --write .
        uses: ./
        with:
          args: --write .
